#define SUDOKU_HALF_WIDTH 16

#define SUDOKU_BLOCK_SIZE 3
#define SUDOKU_GRID_SIZE (SUDOKU_BLOCK_SIZE*SUDOKU_BLOCK_SIZE)

#define SUDOKU_LOW_BIT_MASK ((1 << SUDOKU_GRID_SIZE)-1)
#define SUDOKU_HIGH_BIT_MASK (SUDOKU_LOW_BIT_MASK << SUDOKU_HALF_WIDTH)
